// <auto-generated />
using System;
using Ajudae.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ajudae.Infra.Migrations
{
    [DbContext(typeof(AjudaeContext))]
    partial class AjudaeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ajudae.Domain.Entities.Atividade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Atividades", (string)null);
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.AtividadeVoluntario", b =>
                {
                    b.Property<Guid>("VoluntarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AtividadeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("VoluntarioId", "AtividadeId");

                    b.HasIndex("AtividadeId");

                    b.ToTable("AtividadesVoluntarios", (string)null);
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.Recompensa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValorPontos")
                        .HasColumnType("int");

                    b.Property<Guid?>("VoluntarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VoluntarioId");

                    b.ToTable("Recompensas", (string)null);
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.Voluntario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AreaVoluntariado")
                        .HasColumnType("int");

                    b.Property<int>("AtividadesFeitas")
                        .HasColumnType("int");

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("0");

                    b.Property<DateTime>("DataDeAlteracao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataDeCadastro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pontuacao")
                        .HasColumnType("int");

                    b.Property<bool>("Presencial")
                        .HasColumnType("bit");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Voluntarios", (string)null);
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.AtividadeVoluntario", b =>
                {
                    b.HasOne("Ajudae.Domain.Entities.Atividade", "Atividade")
                        .WithMany("voluntarios")
                        .HasForeignKey("AtividadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ajudae.Domain.Entities.Voluntario", "Voluntario")
                        .WithMany("atividades")
                        .HasForeignKey("VoluntarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Atividade");

                    b.Navigation("Voluntario");
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.Recompensa", b =>
                {
                    b.HasOne("Ajudae.Domain.Entities.Voluntario", null)
                        .WithMany("recompensas")
                        .HasForeignKey("VoluntarioId");
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.Atividade", b =>
                {
                    b.Navigation("voluntarios");
                });

            modelBuilder.Entity("Ajudae.Domain.Entities.Voluntario", b =>
                {
                    b.Navigation("atividades");

                    b.Navigation("recompensas");
                });
#pragma warning restore 612, 618
        }
    }
}
